{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ include "api.namespace" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "api.namespace" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
